#!/bin/bash

deepspeed --include localhost:3 --master_port 25751 train.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path /data/louhaoran/vicuna-1.5-13b/ \
    --lora_enable True \
    --lora_r 128 \
    --lora_alpha 256 \
    --mm_projector_lr 2e-5 \
    --version v1\
    --data_path /data/louhaoran/T+X-T_data/llava/llava_v1_5_mix665k.json \
    --image_folder /data/louhaoran/llava/images/ \
    --vision_tower /data/louhaoran/clip-14-336/ \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio anyres \
    --mm_patch_merge_type spatial_unpad \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.6-13b-pretrain-cnn336-adptive-pooling \
    --num_train_epochs 1 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb

