#!/bin/bash

deepspeed --include localhost:0,1,2,3,4,5,6,7 --master_port 25751 train.py \
    --deepspeed /root/LLaVA-SP/scripts/zero2.json \
    --model_name_or_path /datadisk/llm/vicuna-13b-v1.5/ \
    --version plain \
    --data_path /datadisk/LLaVA-Pretrain/blip_laion_cc_sbu_558k.json  \
    --image_folder /datadisk/LLaVA-Pretrain/images \
    --vision_tower /datadisk/llm/clip-vit-large-patch14-336/ \
    --mm_projector_type mlp2x_gelu \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio anyres \
    --mm_patch_merge_type spatial_unpad \
    --bf16 True \
    --output_dir /datadisk/checkpoints/llava-v1.6-13b-pretrain-cnn336-adptive-pooling \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
